# Generated by Django 5.2.7 on 2025-10-27 13:39

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LaporanJalan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lokasi', django.contrib.gis.db.models.fields.PointField(help_text='Lokasi titik jalan rusak', srid=4326)),
                ('deskripsi', models.TextField(blank=True, help_text='Deskripsi singkat kerusakan', null=True)),
                ('status', models.CharField(choices=[('BARU', 'Baru'), ('DIVERIFIKASI', 'Diverifikasi'), ('DIPERBAIKI', 'Diperbaiki'), ('SELESEI', 'Selesai')], default='BARU', max_length=20)),
                ('tanggal_lapor', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FotoLaporan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='laporan_foto/')),
                ('laporan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foto_set', to='pelaporan.laporanjalan')),
            ],
        ),
    ]
