# Generated by Django 5.2.7 on 2025-12-04 06:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pelaporan', '0002_laporanjalan_email_pelapor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fotolaporan',
            options={'ordering': ['-tanggal_upload'], 'verbose_name': 'Foto Laporan', 'verbose_name_plural': 'Foto Laporan'},
        ),
        migrations.AlterModelOptions(
            name='laporanjalan',
            options={'ordering': ['-tanggal_lapor'], 'verbose_name': 'Laporan Jalan', 'verbose_name_plural': 'Laporan Jalan'},
        ),
        migrations.AddField(
            model_name='fotolaporan',
            name='caption',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='fotolaporan',
            name='tanggal_upload',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laporanjalan',
            name='catatan_admin',
            field=models.TextField(blank=True, help_text='Catatan internal admin', null=True),
        ),
        migrations.AddField(
            model_name='laporanjalan',
            name='jenis_kerusakan',
            field=models.CharField(choices=[('LUBANG', 'Jalan Berlubang'), ('RETAK', 'Jalan Retak'), ('AMBLAS', 'Jalan Amblas'), ('RUSAK_PARAH', 'Rusak Parah'), ('LAINNYA', 'Lainnya')], default='LAINNYA', max_length=20, verbose_name='Jenis Kerusakan'),
        ),
        migrations.AddField(
            model_name='laporanjalan',
            name='tanggal_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='laporanjalan',
            name='tingkat_kerusakan',
            field=models.CharField(choices=[('RINGAN', 'Ringan'), ('SEDANG', 'Sedang'), ('BERAT', 'Berat')], default='SEDANG', max_length=10, verbose_name='Tingkat Kerusakan'),
        ),
        migrations.AlterField(
            model_name='laporanjalan',
            name='status',
            field=models.CharField(choices=[('BARU', 'Baru'), ('DIVERIFIKASI', 'Diverifikasi'), ('DIPERBAIKI', 'Diperbaiki'), ('SELESAI', 'Selesai')], default='BARU', max_length=20),
        ),
    ]
