# Generated by Django 5.2.7 on 2025-12-04 06:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pelaporan', '0003_alter_fotolaporan_options_alter_laporanjalan_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='laporanjalan',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='laporan_jalan', to=settings.AUTH_USER_MODEL, verbose_name='Pelapor (User)'),
        ),
    ]
